/**
 * Shop configuration.
 * meshName must exactly match the node name in the GLTF scene graph
 * (the name set in Blender's Outliner panel before export).
 */
export const SHOPS = [
  {
    meshName: 'test1',
    name: 'WE ARE AEROMINE',
    category: 'DRONE SERVICES',
    icon: '🚁',
    hours: 'Mon – Sun: 08:00 – 21:00',
    description: 'THIS IS THE TEST DESCRIPTION',
    phone: '+30 210 000 0001',
    website: 'www.aeromine.gr',
    photo: null,
  },
  {
    meshName: 'Building_2',
    name: 'Tech Hub',
    category: 'Electronics',
    icon: '📱',
    hours: 'Mon – Sat: 10:00 – 21:00 | Sun: 11:00 – 19:00',
    description: 'Latest gadgets, accessories, and on-site repair services.',
    phone: '+30 210 000 0002',
    website: 'www.techhub-mall.gr',
    photo: '/models/images/techHub.jpg',
  },
  {
    meshName: 'Building_4',
    name: 'FitZone',
    category: 'Gym & Wellness',
    icon: '🏋️',
    hours: 'Mon – Fri: 06:00 – 23:00 | Sat – Sun: 08:00 – 21:00',
    description: 'Full-equipment gym with personal training and yoga classes.',
    phone: '+30 210 000 0003',
    website: 'www.fitzone-mall.gr',
    photo: '/models/images/gym.jpeg',
  },
  {
    meshName: 'Building_11',
    name: 'La Piazza',
    category: 'Restaurant',
    icon: '🍕',
    hours: 'Mon – Sun: 12:00 – 23:00',
    description: 'Authentic Italian cuisine in a warm, relaxed setting.',
    phone: '+30 210 000 0004',
    website: 'www.lapiazza-mall.gr',
    photo: '/models/images/pizza.jpg',
  },
  {
    meshName: 'Building_12',
    name: 'Green Bowl',
    category: 'Health Food',
    icon: '🥗',
    hours: 'Mon – Sun: 09:00 – 20:00',
    description: 'Fresh salads, smoothie bowls, and organic juices.',
    phone: '+30 210 000 0005',
    website: 'www.greenbowl-mall.gr',
    photo: '/models/images/salad.jpeg',
  },
  {
    meshName: 'Building_14',
    name: 'Spark Kids',
    category: 'Toys & Games',
    icon: '🧸',
    hours: 'Mon – Sun: 10:00 – 20:00',
    description: 'Educational toys, games, and weekend activity workshops.',
    phone: '+30 210 000 0006',
    website: 'www.sparkkids-mall.gr',
    photo: '/models/images/toyShop.jpg',
  },
  {
    meshName: 'Central Shops',
    name: 'Central Market',
    category: 'Mixed Retail',
    icon: '🛍️',
    hours: 'Mon – Sun: 09:00 – 22:00',
    description: 'A curated mix of boutique stores in the heart of the mall.',
    phone: '+30 210 000 0007',
    website: 'www.centralmarket-mall.gr',
    photo: null,
  },
  {
    meshName: 'Clothe shops',
    name: 'Fashion District',
    category: 'Fashion',
    icon: '👗',
    hours: 'Mon – Sat: 10:00 – 21:00 | Sun: 11:00 – 19:00',
    description: 'Top fashion brands and seasonal collections under one roof.',
    phone: '+30 210 000 0008',
    website: 'www.fashiondistrict-mall.gr',
    photo: null,
  },
  {
    meshName: 'Village Cinema',
    name: 'Village Cinema',
    category: 'Entertainment',
    icon: '🎬',
    hours: 'Daily: 11:00 – 00:00',
    description: '8-screen multiplex with IMAX, VIP seating, and a full snack bar.',
    phone: '+30 210 000 0009',
    website: 'www.villagecinema.gr',
    photo: null,
  },
];
